### PR TITLE
chore: update to uproot 4

### PR DESCRIPTION
**Pull request by henryiii**
Taken from uproot4, which should be archived eventually.

### CODE REVIEW

**Comment by henryiii** [comment]
Windows only: `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7676: character maps to <undefined>`

I feel like I should know how to fix that, I think by doing something with the codecs package? If you use setup.cfg instead of doing this by hand, does that also fix it, I wonder?

Will look into it tomorrow unless someone knows a quick fix.

**Comment by henryiii** [comment]
Will wait to merge till https://github.com/scikit-hep/uproot4/pull/231 gets accepted or replaced by @jpivarski . At that point, I'll change the patch name to 4.0.1 so that we know to drop it in the next release.

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
39c4561 can be removed once https://github.com/conda-forge/awkward-feedstock/pull/59 is merged and built

**Pull request merged**
